DROP TABLE IF EXISTS boards;

CREATE TABLE boards(
    id SERIAL PRIMARY KEY UNIQUE,
    user_id INTEGER REFERENCES users(id),
    board VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
