DROP TABLE IF EXISTS cards;

CREATE TABLE cards(
    id SERIAL PRIMARY KEY UNIQUE,
    user_id INTEGER,
    board_id INTEGER,
    list_id INTEGER,
    card VARCHAR(300) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
